language: python
python:
  - 3.5
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - pip install coveralls
  - pip install .
script:
  - python setup.py develop && coverage run setup.py test
  - coverage report -m
after_success:
  - coveralls --verbose
